function h_figure = show_fs_lookup_table( lookup_table, codes_to_display, sort_by_hue )
% Displays a window with a table of colors and labels for FreeSurfer's
% auto-parcellation scheme. 
% 
% Usage: 
% SHOW_FS_LOOKUP_TABLE(T) displays the full lookup table. "T" is the lookup
% table structure (with fields code, name, and rgbv, as generated by the 
% "read_fs_color_lookup_table" function). 
% SHOW_FS_LOOKUP_TABLE(T, codes), shows the table only for the selected
% label code list in "codes". It is recommended to input the codes
% corresponding to the vertices presented in the current plot as the full
% list has 1266 labels, most of which are irrelevant. 
% SHOW_FS_LOOKUP_TABLE(T, codes, sort_by_hue) with "sort_by_hue" set to
% TRUE or FALSE determines whether the list will be sorted by hue or by the
% original label order. Default is TRUE. 
% h = SHOW_FS_LOOKUP_TABLE(...) returns the handle to the figure. 
% 
% Written by Edden M. Gerber, lab of Leon Y. Deouell, Hebrew University of
% Jerusalem. 


% Initialize GUI parameters
fig_width = 450;
fig_height = 800;
fig_margin = 20;
color_column_width = 60;
screen_size = get(0,'ScreenSize');

% Handle input
if nargin < 3
    sort_by_hue = true;
end
if nargin < 2 % Show all possible values (quite useless)
    codes_to_display = lookup_table.code;
end
codes_to_display = unique(codes_to_display);

% Get names and color values
code_indexes = [];
for i = 1:length(codes_to_display)
    code_indexes(i) = find(lookup_table.code == codes_to_display(i));
end
names = lookup_table.name(code_indexes);
rgbvalues = lookup_table.rgbv(code_indexes,1:3);

% Get html color tags 
color_cell_gen_html = @(rbg_color) ['<html><table border=0 width=400 bgcolor=',['#' reshape(dec2hex(round(rbg_color),2)',1,[])],'><TR><TD></TD></TR> </table></html>'];
for i = 1:length(rgbvalues)
    colorcell_html{i} = color_cell_gen_html(rgbvalues(i,:));
end

% Sort by hue
if sort_by_hue
    hsv_values = rgb2hsv(rgbvalues/255);
    [~, sort_order] = sort(hsv_values(:,1));
    colorcell_html = colorcell_html(sort_order);
    names = names(sort_order);
end

% Generate data table
table_data = [colorcell_html' names];

% Display figure
fig_pos = [screen_size(3)-fig_width screen_size(4)-fig_height fig_width fig_height];
tab_pos = [fig_margin fig_margin fig_width-2*fig_margin fig_height-2*fig_margin];
h_figure = figure('Name','FreeSurfer Auto-Parcellation Color Lookup Table','Position',fig_pos);
h_table = uitable(h_figure,'Data',table_data,'Position',tab_pos,'ColumnWidth',{color_column_width, tab_pos(3)-color_column_width-60},...
    'ColumnName',{'Color','Label'});

% Resize table when resizing figure
set(h_figure,'SizeChangedFcn',@fig_resize_fcn)
    function fig_resize_fcn(hObject, callbackdata)
        fig_pos = get(hObject,'Position');
        fig_width = fig_pos(3);
        fig_height = fig_pos(4);
        tab_pos = [fig_margin fig_margin fig_width-2*fig_margin fig_height-2*fig_margin];
%         set(h_table,'Position',tab_pos);
        set(h_table,'Position',tab_pos,'ColumnWidth',{color_column_width, tab_pos(3)-color_column_width-60});
    end
end

